apiVersion: apps/v1
kind: Deployment
metadata:
  name: seeft-web
  namespace: seeft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seeft-web
  template:
    metadata:
      labels:
        app: seeft-web
    spec:
      containers:
        - name: seeft-cloudflared-container
          image: cloudflare/cloudflared:latest
          args: ["tunnel", "run"]
          volumeMounts:
            - name: seeft-web-config
              mountPath: /home/nonroot/.cloudflared/
              readOnly: true
      volumes:
        - name: seeft-web-config
          secret:
            secretName: cloudflared-configs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seeft-mobile
  namespace: seeft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seeft-mobile
  template:
    metadata:
      labels:
        app: seeft-mobile
    spec:
      imagePullSecrets:
      - name: harbor-creds
      containers:
      - name: seeft-mobile-container
        image: reg.nutmeg.cloud/seeft/mobile:c6247fe
        command: ["python3", "./python/server.py"]
        ports:
          - containerPort: 45029
        env:
          - name: NEXT_PUBLIC_APP_ENV
            value: "production"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seeft-admin
  namespace: seeft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seeft-admin
  template:
    metadata:
      labels:
        app: seeft-admin
    spec:
      imagePullSecrets:
      - name: harbor-creds
      containers:
      - name: seeft-admin-container
        image: reg.nutmeg.cloud/seeft/admin:c6247fe
        command: ["sh", "-c", "npm install && npm run dev"]
        ports:
          - containerPort: 3000
        env:
          - name: NEXT_PUBLIC_APP_ENV
            value: "production"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seeft-api
  namespace: seeft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seeft-api
  template:
    metadata:
      labels:
        app: seeft-api
    spec:
      imagePullSecrets:
      - name: harbor-creds
      containers:
      - name: seeft-api-container
        image: reg.nutmeg.cloud/seeft/api:c6247fe
        command: ["go", "run", "main.go"]
        ports:
          - containerPort: 1234
        envFrom:
          - secretRef:
              name: seeft-api-env
